CREATE TABLE courses (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  course_code INTEGER NOT NULL,
  course_name TEXT NOT NULL,
  course_desc TEXT,
  course_level TEXT,
  college_credits INTEGER NOT NULL,
  department TEXT,
  hs_credits DECIMAL,
  hs_department TEXT,
  culturally_relevant BOOLEAN,
  isDeleted BOOLEAN DEFAULT false NOT NULL,
  isActive BOOLEAN DEFAULT true NOT NULL,
  updatedAt TIMESTAMPTZ DEFAULT now() NOT NULL
);