CREATE TABLE higheredinstitutions (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  institution_type TEXT NOT NULL,
  short_name TEXT,
  cde_number INTEGER, 
  cde_name TEXT,
  isCE BOOLEAN NOT NULL, 
  isDE BOOLEAN NOT NULL, 
  isDeleted BOOLEAN DEFAULT false NOT NULL,
  isActive BOOLEAN DEFAULT true NOT NULL,
  updatedAt TIMESTAMPTZ DEFAULT now() NOT NULL
);