/* citext allows for case insensitive searching*/
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  last_name TEXT NOT NULL,
  first_name TEXT NOT NULL,
  email CITEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
	role TEXT NOT NULL,
  school_id INTEGER 
    REFERENCES highschools(id) ON DELETE SET NULL,
  higherEdInstitution_id INTEGER 
    REFERENCES higheredinstitutions(id) ON DELETE SET NULL,
	isDeleted BOOLEAN DEFAULT false NOT NULL,
  isActive BOOLEAN DEFAULT true NOT NULL,
  updatedAt TIMESTAMPTZ DEFAULT now() NOT NULL
);