CREATE TABLE courserequests (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  higheredinstitution_id INTEGER  
    REFERENCES higheredinstitutions(id) ON DELETE CASCADE NOT NULL,
  school_id INTEGER
    REFERENCES highschools(id) ON DELETE CASCADE NOT NULL,
  course_id INTEGER
    REFERENCES courses(id) ON DELETE CASCADE NOT NULL,
  course_type TEXT NOT NULL,
  instructor_type TEXT NOT NULL,
  instructor_id INTEGER
    REFERENCES users(id) ON DELETE SET NULL,
  school_year INTEGER NOT NULL,
  academic_term TEXT NOT NULL,
  period TEXT,
  days TEXT,
  times TEXT,
  projected_enrollment INTEGER,
  isDeleted BOOLEAN DEFAULT false NOT NULL,
  isActive BOOLEAN DEFAULT true NOT NULL,
  onWishlist BOOLEAN DEFAULT false,
  updatedAt TIMESTAMPTZ DEFAULT now() NOT NULL
);