BEGIN;

TRUNCATE TABLE
  schools
  RESTART IDENTITY CASCADE;

INSERT INTO schools (school_num, school_name, network)
VALUES  
  (450,'Abraham Lincoln High School','Southwest'),
  (451,'East High School','Central'),
  (452,'George Washington High School','Near Northeast'),
  (453,'John F. Kennedy High School','Southwest'),
  (455,'North High School','Northwest'),
  (456,'South High School','Southeast'),
  (457,'Thomas Jefferson High School','Southeast'),
  (460,'KIPP Northeast Denver Leadership Academy','Charter'),
  (461,'DCIS HS','Northwest'),
  (462,'DSST: Green Valley Ranch HS','Charter'),
  (463,'Bruce Randolph HS','Central'),
  (464,'Manual High School','Far Northeast'),
  (465,'Kunsmiller Creative Arts Academy HS','Southwest'),
  (466,'DCIS at Montbello HS','Far Northeast'),
  (467,'Noel Community Arts HS','Far Northeast'),
  (468,'Collegiate Preparatory Academy','Far Northeast'),
  (469,'Dr. Martin Luther King Jr. Early College HS','Far Northeast'),
  (470,'DELTA HS','Near Northeast'),
  (471,'Northeast Early College','Far Northeast'),
  (472,'DSST: Cole HS','Charter'),
  (473,'Florence Crittenton High School','Southwest'),
  (475,'Denver School of Arts HS','Near Northeast'),
  (478,'Ridge View Academy Charter School','Charter'),
  (479,'Colorado High School Charter','Charter'),
  (481,'DSST: Montview HS','Charter'),
  (484,'Denver Online High School','Northwest'),
  (488,'AUL Denver','Charter'),
  (490,'Colorado High School Charter – GES','Charter'),
  (497,'Denver Justice High School','Charter'),
  (498,'KIPP Denver Collegiate High School','Charter'),
  (499,'RiseUp Community School','Charter'),
  (504,'DS Innovation & Sustainable Design','Central'),
  (506,'Respect Academy','Southwest'),
  (507,'North High School Engagement Center','Northwest'),
  (509,'Montbello Career and Technical High School','Far Northeast'),
  (510,'West Early College HS','Northwest'),
  (511,'West Leadership Academy HS','Northwest'),
  (513,'STRIVE Prep - SMART Academy','Charter'),
  (514,'Denver Montessori Senior HS','Northwest'),
  (515,'Compassion Road Academy','Central'),
  (516,'EXCEL Academy','Southwest'),
  (518,'DSST: Byers HS','Charter'),
  (519,'Northfield High School','Innovation Zone'),
  (520,'Girls Athletic Leadership HS','Charter'),
  (521,'DSST: College View HS','Charter'),
  (522,'Legacy Options High School','Far Northeast'),
  (523,'DSST: Conservatory Green HS','Charter'),
  (525,'STRIVE Prep - RISE','Charter'),
  (532,'5280 High School','Charter'),
  (533,'The CUBE','Charter'),
  (602,'Emily Griffith High School','Central'),
  (604,'Summit Academy HS','Southwest'),
  (605,'CEC Early College','Northwest'),
  (609,'Vista Academy HS','Far Northeast'),
  (610,'Denver Center for 21stCentury Learning at Wyman HS','Central'),
  (611,'ASCENT','ASCENT'),
  (671,'PREP Academy HS','Central'),
  (682,'Contemporary Learning Academy HS','Central');
  
COMMIT;