BEGIN;

TRUNCATE TABLE
  highschools
  RESTART IDENTITY CASCADE;

INSERT INTO highschools (school_num, school_name, network)
VALUES  
  (450,'Abraham Lincoln High School','SOUTHWEST'),
  (451,'East High School','CENTRAL'),
  (452,'George Washington High School','NEAR_NORTHEAST'),
  (453,'John F. Kennedy High School','SOUTHWEST'),
  (455,'North High School','NORTHWEST'),
  (456,'South High School','SOUTHEAST'),
  (457,'Thomas Jefferson High School','SOUTHEAST'),
  (460,'KIPP Northeast Denver Leadership Academy','CHARTER'),
  (461,'DCIS HS','NORTHWEST'),
  (462,'DSST: Green Valley Ranch HS','CHARTER'),
  (463,'Bruce Randolph HS','CENTRAL'),
  (464,'Manual High School','FAR_NORTHEAST'),
  (465,'Kunsmiller Creative Arts Academy HS','SOUTHWEST'),
  (466,'DCIS at Montbello HS','FAR_NORTHEAST'),
  (467,'Noel Community Arts HS','FAR_NORTHEAST'),
  (468,'Collegiate Preparatory Academy','FAR_NORTHEAST'),
  (469,'Dr. Martin Luther King Jr. Early College HS','FAR_NORTHEAST'),
  (470,'DELTA HS','NEAR_NORTHEAST'),
  (471,'Northeast Early College','FAR_NORTHEAST'),
  (472,'DSST: Cole HS','CHARTER'),
  (473,'Florence Crittenton High School','SOUTHWEST'),
  (475,'Denver School of Arts HS','NEAR_NORTHEAST'),
  (478,'Ridge View Academy Charter School','CHARTER'),
  (479,'Colorado High School Charter','CHARTER'),
  (481,'DSST: Montview HS','CHARTER'),
  (484,'Denver Online High School','NORTHWEST'),
  (488,'AUL Denver','CHARTER'),
  (490,'Colorado High School Charter – GES','CHARTER'),
  (497,'Denver Justice High School','CHARTER'),
  (498,'KIPP Denver Collegiate High School','CHARTER'),
  (499,'RiseUp Community School','CHARTER'),
  (504,'DS Innovation & Sustainable Design','CENTRAL'),
  (506,'Respect Academy','SOUTHWEST'),
  (507,'North High School Engagement Center','NORTHWEST'),
  (509,'Montbello Career and Technical High School','FAR_NORTHEAST'),
  (510,'West Early College HS','NORTHWEST'),
  (511,'West Leadership Academy HS','NORTHWEST'),
  (513,'STRIVE Prep - SMART Academy','CHARTER'),
  (514,'Denver Montessori Senior HS','NORTHWEST'),
  (515,'Compassion Road Academy','CENTRAL'),
  (516,'EXCEL Academy','SOUTHWEST'),
  (518,'DSST: Byers HS','CHARTER'),
  (519,'Northfield High School','INNOVATION_ZONE'),
  (520,'Girls Athletic Leadership HS','CHARTER'),
  (521,'DSST: College View HS','CHARTER'),
  (522,'Legacy Options High School','FAR_NORTHEAST'),
  (523,'DSST: Conservatory Green HS','CHARTER'),
  (525,'STRIVE Prep - RISE','CHARTER'),
  (532,'5280 High School','CHARTER'),
  (533,'The CUBE','CHARTER'),
  (602,'Emily Griffith High School','CENTRAL'),
  (604,'Summit Academy HS','SOUTHWEST'),
  (605,'CEC Early College','NORTHWEST'),
  (609,'Vista Academy HS','FAR_NORTHEAST'),
  (610,'Denver Center for 21stCentury Learning at Wyman HS','CENTRAL'),
  (611,'ASCENT','ASCENT'),
  (671,'PREP Academy HS','CENTRAL'),
  (682,'Contemporary Learning Academy HS','CENTRAL');
  
COMMIT;